# Generated by Django 4.1 on 2023-02-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rec", "0002_apartments_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="priceinfo",
            name="per_price",
        ),
    ]
