# Generated by Django 4.1 on 2023-02-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rec", "0003_remove_priceinfo_per_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartments",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
