# Generated by Django 4.1 on 2022-11-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rec", "0006_priceinfo_unique aprart price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartments",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
