# Generated by Django 4.1 on 2022-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rec", "0007_alter_apartments_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="priceinfo",
            name="unique aprart price",
        ),
        migrations.AddField(
            model_name="priceinfo",
            name="transaction_style",
            field=models.CharField(default="매매", max_length=10),
        ),
        migrations.AddConstraint(
            model_name="priceinfo",
            constraint=models.UniqueConstraint(
                fields=("apart", "date"), name="unique apart price"
            ),
        ),
    ]
